name: HCL AppScan on Cloud (ASoC) SAST & SCA Scan

on:
  push:
    branches: [ "main", "master", "VS_2010" ]
  pull_request:
    branches: [ "main", "master", "VS_2010" ]
  workflow_dispatch:

jobs:
  AppScan-SAST-SCA:
    name: Run AppScan SAST & SCA Scan
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      # --- TAMBAHAN KHUSUS JAVASCRIPT / NODE.JS ---
      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 3. Install Dependencies
        run: npm install --legacy-peer-deps

      # --- 1. PROSES SCANNING SAST (STATIC ANALYSIS) ---
      - name: 4. Run AppScan SAST Scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.1.0
        continue-on-error: true
        with:
          asoc_key: ${{ secrets.ASOC2_ID }}
          asoc_secret: ${{ secrets.ASOC2_SECRET }}
          application_id: "93451ffb-ffa0-444d-a8ee-4853c0bac987"
          scan_name: "SAST_ExpressJS_PNM2_with SCA"
          static_analysis_only: true
          wait_for_analysis: false

      # --- 2. PROSES SCANNING SCA (OPEN SOURCE ANALYSIS) ---
      - name: 5. Run AppScan SCA (Open Source) Scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.1.0
        continue-on-error: true
        with:
          asoc_key: ${{ secrets.ASOC2_ID }}
          asoc_secret: ${{ secrets.ASOC2_SECRET }}
          application_id: "93451ffb-ffa0-444d-a8ee-4853c0bac987"
          scan_name: "SCA_ExpressJS_PNM2_with SCA"
          open_source_only: true
          wait_for_analysis: false
